spring:
  application:
    name: url-cut-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/url-dependencies
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  flyway:
    url: jdbc:postgresql://postgres:5432/url-dependencies
    user: postgres
    password: postgres
service:
   url-domain: localhost:8080/api/v1/super-url-cutter