create table UrlDependencies(
    id bigint primary key generated by default as identity,
    original_url varchar not null,
    alias varchar not null,
    shortened_url varchar unique not null,
    expiration_time timestamp
)